title: Your awesome title
author:
  name: Scillman
  email: Scillman@users.noreply.github.com

description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: /
domain: scillman.github.io
url: http://scillman.github.io
# twitter_username: Scillman
github_username: Scillman

# Build settings
#remote_theme: jekyll/minima
theme: null
#theme: minima
#minima:
#  skin: dark
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

# Configuration
lsi: false
safe: true
source: ./docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
#  list_indent: 4
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
#    span:
#      line_numbers: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - dev/

collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/
  tutorials:
    output: true
    permalink: /tutorial/:path/
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
